### ISSUE TITLE
Outsource Entity Information into a file

### ISSUE THREAD

**Issue by ChrisThor** [ChrisThor/Gate-To-Gods#10]
The file can specify any entity they want, including the player. An entity specification can look like this:
```
Person:
  healthPoints: 40
  damage: (10)
  fieldOfVision: 3
  hostile: false
  name: Person
```
`healthPoints` will specify the maximum amount of HP an entity can have.
`damage` specifies the damage with which an entity can attack. This option also allows a range like `  damage: (1-3)`. In this case, an entity will deal a random amount of damage between 1 and 3.
`fieldOfVision` specifies the distance an entity can see. A number over 5 is not advised.
`hostile` has only an effect on entities that are not a player. Defines the symbol (p for peaceful and E for enemy) and their default behaviour.
`name` is the Name with which that entity will be displayed in a message.
